name = "zepio-erp"
account_id = "441473cfd291e56f372ff4b4640ee88d"
main = "server/src/worker.js"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "client/dist"
binding = "ASSETS"

[vars]
NODE_ENV = "production"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "zepio-erp-db"
database_id = "1432ef28-2d57-4477-825a-a67464f00a2d"
