name = "zepio-erp"
account_id = "441473cfd291e56f372ff4b4640ee88d"
main = "server/src/worker.js"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "client/dist"
binding = "ASSETS"

[vars]
NODE_ENV = "production"
